/*
 * anura_main.c  ——  Complete Anura Signal Board Firmware
 * ───────────────────────────────────────────────────────
 * MCU    : STM32F407VGT6
 * Board  : Anura Signal Board (Leyva-Cortes, Hu, Kepecs)
 *
 * ── Pin mapping ──────────────────────────────────────────
 *  PA2  ADC1_IN2  → LEFT_OUTER_MIC_IN   (MEMS FF reference L)
 *  PA3  ADC1_IN3  → RIGHT_OUTER_MIC_IN  (MEMS FF reference R)
 *  PA6  ADC1_IN6  → LEFT_AUDIO_IN       (source audio + error ref L)
 *  PA7  ADC1_IN7  → RIGHT_AUDIO_IN      (source audio + error ref R)
 *  PA4  DAC_OUT1  → LEFT_AUDIO_OUT
 *  PA5  DAC_OUT2  → RIGHT_AUDIO_OUT
 *  PA8  GPIO_IN   → MODE_BUTTON_IN      (active HIGH, debounced)
 *  PB0  TIM3_CH3  → MONO_MIC_PWM_OUT   (→ RC filter → TRRS → laptop)
 *  PB4  GPIO_OUT  → AD_CTRL_OUT         (HIGH = digital, LOW = analog)
 *  PB6  I2C1_SCL  → OLED + BMS SCL
 *  PB7  I2C1_SDA  → OLED + BMS SDA
 *
 * ── Modes (button cycles 0→1→2→3→0) ─────────────────────
 *  0 — Passthrough   : audio in → audio out, no processing
 *  1 — Analog ANC    : AD_CTRL LOW, LF356 subcircuit handles it
 *  2 — Digital ANC   : NLMS feedforward, outer MEMS mics
 *  3 — Translation   : digital ANC + PWM out → laptop
 *
 * ── Build flags ──────────────────────────────────────────
 *  -DARM_MATH_CM4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -O2
 *
 * ── CubeMX peripherals needed ────────────────────────────
 *  ADC1  scan, 4ch, DMA2 stream0, timer-triggered (TIM2)
 *  DAC   ch1+ch2, DMA, timer-triggered (TIM2)
 *  TIM2  sample rate trigger (ARR=1749 for 48kHz @ 84MHz)
 *  TIM3  PWM CH3 on PB0 (ARR=4095)
 *  TIM4  1ms timebase for button debounce (ARR=83999 @ 84MHz)
 *  I2C1  fast mode 400kHz, PB6/PB7
 *  GPIO  PA8 input pull-down, PB4 output
 * ─────────────────────────────────────────────────────────
 */

#include "main.h"
#include "arm_math.h"
#include <string.h>
#include <stdio.h>

/* ══════════════════════════════════════════════════════════
 *  TUNEABLE PARAMETERS
 * ══════════════════════════════════════════════════════════ */
#define ANC_FILTER_TAPS         64
#define ANC_MU                  0.005f
#define ANC_BLOCK_SIZE          32
#define SAMPLE_RATE             48000

#define ADC_MIDPOINT            2048
#define ADC_SCALE               (1.0f / 2048.0f)
#define DAC_MIDPOINT            2048
#define DAC_SCALE               2047.0f

#define NLMS_BETA               0.999f
#define NLMS_EPSILON            1e-4f

#define PWM_PERIOD              4095

#define BUTTON_DEBOUNCE_MS      50
#define NUM_MODES               4

/* ── I2C addresses ────────────────────────────────────────
 * SSD1306 OLED: 0x3C (7-bit) → 0x78 shifted
 * BMS: replace 0x6B with your actual chip address once confirmed
 * ───────────────────────────────────────────────────────── */
#define OLED_I2C_ADDR           (0x3C << 1)
#define BMS_I2C_ADDR            (0x6B << 1)   /* TODO: confirm with power PCB */

/* BMS register placeholders — swap in real addresses once chip confirmed */
#define BMS_REG_SOC             0x00   /* state of charge (%) */
#define BMS_REG_VOLTAGE         0x01   /* battery voltage      */

/* ══════════════════════════════════════════════════════════
 *  ADC / DAC BUFFER TYPES
 * ══════════════════════════════════════════════════════════ */
/* 4 ADC channels: ref_l, ref_r, src_l, src_r */
typedef struct {
    uint16_t ref_l;    /* PA2 ADC1_IN2  outer MEMS mic left  (FF ref)  */
    uint16_t ref_r;    /* PA3 ADC1_IN3  outer MEMS mic right (FF ref)  */
    uint16_t src_l;    /* PA6 ADC1_IN6  source audio L + error ref     */
    uint16_t src_r;    /* PA7 ADC1_IN7  source audio R + error ref     */
} AdcFrame;

typedef struct {
    uint16_t left;
    uint16_t right;
} DacFrame;

#define ADC_CHANNELS            4
#define ADC_BUF_FRAMES          (ANC_BLOCK_SIZE * 2)
#define ADC_BUF_LEN             (ADC_BUF_FRAMES * ADC_CHANNELS)

static AdcFrame adc_buf[ADC_BUF_FRAMES];
static DacFrame dac_buf[ADC_BUF_FRAMES];

/* ══════════════════════════════════════════════════════════
 *  MODE STATE
 * ══════════════════════════════════════════════════════════ */
typedef enum {
    MODE_PASSTHROUGH  = 0,
    MODE_ANALOG_ANC   = 1,
    MODE_DIGITAL_ANC  = 2,
    MODE_TRANSLATION  = 3
} AnuraMode;

static volatile AnuraMode current_mode = MODE_PASSTHROUGH;

/* ══════════════════════════════════════════════════════════
 *  LMS FILTER STATE
 * ══════════════════════════════════════════════════════════ */
typedef struct {
    float32_t weights[ANC_FILTER_TAPS];
    float32_t delay[ANC_FILTER_TAPS];
    uint32_t  head;
    float32_t power;
} LmsChannel;

static LmsChannel lms_left;
static LmsChannel lms_right;

/* ══════════════════════════════════════════════════════════
 *  HAL HANDLES (generated by CubeMX in main.c)
 * ══════════════════════════════════════════════════════════ */
extern ADC_HandleTypeDef  hadc1;
extern DAC_HandleTypeDef  hdac;
extern TIM_HandleTypeDef  htim2;   /* sample rate trigger  */
extern TIM_HandleTypeDef  htim3;   /* PWM mono mic out     */
extern TIM_HandleTypeDef  htim4;   /* 1ms button debounce  */
extern I2C_HandleTypeDef  hi2c1;   /* OLED + BMS           */


/* ══════════════════════════════════════════════════════════
 *  CONVERSION HELPERS
 * ══════════════════════════════════════════════════════════ */
static inline float32_t adc_to_float(uint16_t raw)
{
    return (float32_t)((int32_t)raw - ADC_MIDPOINT) * ADC_SCALE;
}

static inline uint16_t float_to_dac(float32_t s)
{
    if      (s >  1.0f) s =  1.0f;
    else if (s < -1.0f) s = -1.0f;
    return (uint16_t)((int32_t)(s * DAC_SCALE) + DAC_MIDPOINT);
}


/* ══════════════════════════════════════════════════════════
 *  LMS / NLMS
 * ══════════════════════════════════════════════════════════ */
static void lms_init(LmsChannel *ch)
{
    memset(ch->weights, 0, sizeof(ch->weights));
    memset(ch->delay,   0, sizeof(ch->delay));
    ch->head  = 0;
    ch->power = 1.0f;
}

/*
 * lms_process — feedforward NLMS step
 *
 * x : feedforward reference (outer MEMS mic)
 * e : error reference (audio_in — what leaked into ear after speaker output)
 *     Since we have no inner mic, we use the source audio signal as a
 *     proxy error: once ANC converges, src should contain mostly speech.
 *
 * returns: predicted anti-noise sample
 */
static float32_t lms_process(LmsChannel *ch, float32_t x, float32_t e)
{
    ch->delay[ch->head] = x;

    float32_t y = 0.0f;
    uint32_t k = ch->head;
    for (uint32_t i = 0; i < ANC_FILTER_TAPS; i++) {
        y += ch->weights[i] * ch->delay[k];
        k  = (k == 0) ? (ANC_FILTER_TAPS - 1) : (k - 1);
    }

    ch->power = NLMS_BETA * ch->power + (1.0f - NLMS_BETA) * (x * x);
    float32_t mu_norm = ANC_MU / (ch->power + NLMS_EPSILON);

    k = ch->head;
    for (uint32_t i = 0; i < ANC_FILTER_TAPS; i++) {
        ch->weights[i] += 2.0f * mu_norm * e * ch->delay[k];
        k = (k == 0) ? (ANC_FILTER_TAPS - 1) : (k - 1);
    }

    ch->head = (ch->head + 1) % ANC_FILTER_TAPS;
    return y;
}


/* ══════════════════════════════════════════════════════════
 *  AUDIO PROCESSING BLOCKS
 * ══════════════════════════════════════════════════════════ */

/* Mode 0 — pure passthrough, no processing */
static void process_passthrough(const AdcFrame *in, DacFrame *out)
{
    for (uint32_t n = 0; n < ANC_BLOCK_SIZE; n++) {
        out[n].left  = in[n].src_l;
        out[n].right = in[n].src_r;
    }
}

/*
 * Mode 2 & 3 — digital ANC
 * ref = outer MEMS mic (feedforward reference)
 * src = source audio in (used as error proxy — see lms_process note)
 * out = src - anti_noise
 */
static void process_digital_anc(const AdcFrame *in, DacFrame *out,
                                 uint8_t enable_pwm_out)
{
    for (uint32_t n = 0; n < ANC_BLOCK_SIZE; n++) {
        float32_t ref_l = adc_to_float(in[n].ref_l);
        float32_t ref_r = adc_to_float(in[n].ref_r);
        float32_t src_l = adc_to_float(in[n].src_l);
        float32_t src_r = adc_to_float(in[n].src_r);

        float32_t anti_l = lms_process(&lms_left,  ref_l, src_l);
        float32_t anti_r = lms_process(&lms_right, ref_r, src_r);

        out[n].left  = float_to_dac(src_l - anti_l);
        out[n].right = float_to_dac(src_r - anti_r);

        /* Mode 3: send combined outer mics as mono to TRRS → laptop */
        if (enable_pwm_out) {
            float32_t mono = (ref_l + ref_r) * 0.5f;
            uint16_t pwm_val = (uint16_t)((mono + 1.0f) * 0.5f * PWM_PERIOD);
            __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_3, pwm_val);
        }
    }
}

/* Mode 1 — analog ANC: STM32 does nothing, LF356 subcircuit handles it.
 * DAC outputs midpoint (silence) so it doesn't interfere. */
static void process_analog_anc(DacFrame *out)
{
    for (uint32_t n = 0; n < ANC_BLOCK_SIZE; n++) {
        out[n].left  = DAC_MIDPOINT;
        out[n].right = DAC_MIDPOINT;
    }
}


/* ══════════════════════════════════════════════════════════
 *  AD_CTRL SWITCHING
 * ══════════════════════════════════════════════════════════ */
static void set_ad_ctrl(uint8_t digital)
{
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4,
                      digital ? GPIO_PIN_SET : GPIO_PIN_RESET);
}


/* ══════════════════════════════════════════════════════════
 *  MODE SWITCHING
 * ══════════════════════════════════════════════════════════ */
static void apply_mode(AnuraMode mode)
{
    switch (mode) {
        case MODE_PASSTHROUGH:
            set_ad_ctrl(1);   /* digital path so STM32 can pass audio through */
            break;
        case MODE_ANALOG_ANC:
            set_ad_ctrl(0);   /* hand off to LF356 analog subcircuit */
            break;
        case MODE_DIGITAL_ANC:
            set_ad_ctrl(1);
            lms_init(&lms_left);    /* reset weights on mode entry */
            lms_init(&lms_right);
            break;
        case MODE_TRANSLATION:
            set_ad_ctrl(1);
            lms_init(&lms_left);
            lms_init(&lms_right);
            HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3);
            break;
    }
}


/* ══════════════════════════════════════════════════════════
 *  DMA CALLBACKS — called from ISR, must be fast
 * ══════════════════════════════════════════════════════════ */
static void dispatch_block(const AdcFrame *in, DacFrame *out)
{
    switch (current_mode) {
        case MODE_PASSTHROUGH:
            process_passthrough(in, out);
            break;
        case MODE_ANALOG_ANC:
            process_analog_anc(out);
            break;
        case MODE_DIGITAL_ANC:
            process_digital_anc(in, out, 0);
            break;
        case MODE_TRANSLATION:
            process_digital_anc(in, out, 1);
            break;
    }
}

void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
        dispatch_block(&adc_buf[0], &dac_buf[0]);
}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
        dispatch_block(&adc_buf[ANC_BLOCK_SIZE], &dac_buf[ANC_BLOCK_SIZE]);
}


/* ══════════════════════════════════════════════════════════
 *  BUTTON HANDLING
 *  PA8, active HIGH, debounced via TIM4 1ms tick
 * ══════════════════════════════════════════════════════════ */
static volatile uint32_t btn_tick        = 0;
static volatile uint8_t  btn_last_state  = 0;
static volatile uint8_t  btn_pending     = 0;

/* Call from TIM4 period elapsed callback (1ms) */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance != TIM4) return;

    uint8_t state = HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_8);

    if (state && !btn_last_state) {
        /* rising edge — start debounce timer */
        btn_tick = 0;
    }
    if (state) {
        btn_tick++;
        if (btn_tick == BUTTON_DEBOUNCE_MS && !btn_pending) {
            btn_pending = 1;
        }
    } else {
        btn_tick = 0;
    }
    btn_last_state = state;
}

static void button_check(void)
{
    if (!btn_pending) return;
    btn_pending = 0;

    AnuraMode next = (AnuraMode)((current_mode + 1) % NUM_MODES);

    /* Stop PWM if leaving translation mode */
    if (current_mode == MODE_TRANSLATION)
        HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_3);

    current_mode = next;
    apply_mode(next);
}


/* ══════════════════════════════════════════════════════════
 *  SSD1306 OLED  (128×64, I2C)
 *  Minimal driver — no external library needed
 * ══════════════════════════════════════════════════════════ */
#define OLED_WIDTH   128
#define OLED_HEIGHT  64
#define OLED_PAGES   (OLED_HEIGHT / 8)

static uint8_t oled_buf[OLED_WIDTH * OLED_PAGES];

/* 5×7 font — ASCII 32–127 */
static const uint8_t font5x7[][5] = {
    {0x00,0x00,0x00,0x00,0x00}, /* ' ' */
    {0x00,0x00,0x5F,0x00,0x00}, /* '!' */
    {0x00,0x07,0x00,0x07,0x00}, /* '"' */
    {0x14,0x7F,0x14,0x7F,0x14}, /* '#' */
    {0x24,0x2A,0x7F,0x2A,0x12}, /* '$' */
    {0x23,0x13,0x08,0x64,0x62}, /* '%' */
    {0x36,0x49,0x55,0x22,0x50}, /* '&' */
    {0x00,0x05,0x03,0x00,0x00}, /* ''' */
    {0x00,0x1C,0x22,0x41,0x00}, /* '(' */
    {0x00,0x41,0x22,0x1C,0x00}, /* ')' */
    {0x08,0x2A,0x1C,0x2A,0x08}, /* '*' */
    {0x08,0x08,0x3E,0x08,0x08}, /* '+' */
    {0x00,0x50,0x30,0x00,0x00}, /* ',' */
    {0x08,0x08,0x08,0x08,0x08}, /* '-' */
    {0x00,0x60,0x60,0x00,0x00}, /* '.' */
    {0x20,0x10,0x08,0x04,0x02}, /* '/' */
    {0x3E,0x51,0x49,0x45,0x3E}, /* '0' */
    {0x00,0x42,0x7F,0x40,0x00}, /* '1' */
    {0x42,0x61,0x51,0x49,0x46}, /* '2' */
    {0x21,0x41,0x45,0x4B,0x31}, /* '3' */
    {0x18,0x14,0x12,0x7F,0x10}, /* '4' */
    {0x27,0x45,0x45,0x45,0x39}, /* '5' */
    {0x3C,0x4A,0x49,0x49,0x30}, /* '6' */
    {0x01,0x71,0x09,0x05,0x03}, /* '7' */
    {0x36,0x49,0x49,0x49,0x36}, /* '8' */
    {0x06,0x49,0x49,0x29,0x1E}, /* '9' */
    {0x00,0x36,0x36,0x00,0x00}, /* ':' */
    {0x00,0x56,0x36,0x00,0x00}, /* ';' */
    {0x08,0x14,0x22,0x41,0x00}, /* '<' */
    {0x14,0x14,0x14,0x14,0x14}, /* '=' */
    {0x00,0x41,0x22,0x14,0x08}, /* '>' */
    {0x02,0x01,0x51,0x09,0x06}, /* '?' */
    {0x32,0x49,0x79,0x41,0x3E}, /* '@' */
    {0x7E,0x11,0x11,0x11,0x7E}, /* 'A' */
    {0x7F,0x49,0x49,0x49,0x36}, /* 'B' */
    {0x3E,0x41,0x41,0x41,0x22}, /* 'C' */
    {0x7F,0x41,0x41,0x22,0x1C}, /* 'D' */
    {0x7F,0x49,0x49,0x49,0x41}, /* 'E' */
    {0x7F,0x09,0x09,0x09,0x01}, /* 'F' */
    {0x3E,0x41,0x49,0x49,0x7A}, /* 'G' */
    {0x7F,0x08,0x08,0x08,0x7F}, /* 'H' */
    {0x00,0x41,0x7F,0x41,0x00}, /* 'I' */
    {0x20,0x40,0x41,0x3F,0x01}, /* 'J' */
    {0x7F,0x08,0x14,0x22,0x41}, /* 'K' */
    {0x7F,0x40,0x40,0x40,0x40}, /* 'L' */
    {0x7F,0x02,0x0C,0x02,0x7F}, /* 'M' */
    {0x7F,0x04,0x08,0x10,0x7F}, /* 'N' */
    {0x3E,0x41,0x41,0x41,0x3E}, /* 'O' */
    {0x7F,0x09,0x09,0x09,0x06}, /* 'P' */
    {0x3E,0x41,0x51,0x21,0x5E}, /* 'Q' */
    {0x7F,0x09,0x19,0x29,0x46}, /* 'R' */
    {0x46,0x49,0x49,0x49,0x31}, /* 'S' */
    {0x01,0x01,0x7F,0x01,0x01}, /* 'T' */
    {0x3F,0x40,0x40,0x40,0x3F}, /* 'U' */
    {0x1F,0x20,0x40,0x20,0x1F}, /* 'V' */
    {0x3F,0x40,0x38,0x40,0x3F}, /* 'W' */
    {0x63,0x14,0x08,0x14,0x63}, /* 'X' */
    {0x07,0x08,0x70,0x08,0x07}, /* 'Y' */
    {0x61,0x51,0x49,0x45,0x43}, /* 'Z' */
    {0x00,0x7F,0x41,0x41,0x00}, /* '[' */
    {0x02,0x04,0x08,0x10,0x20}, /* '\' */
    {0x00,0x41,0x41,0x7F,0x00}, /* ']' */
    {0x04,0x02,0x01,0x02,0x04}, /* '^' */
    {0x40,0x40,0x40,0x40,0x40}, /* '_' */
    {0x00,0x01,0x02,0x04,0x00}, /* '`' */
    {0x20,0x54,0x54,0x54,0x78}, /* 'a' */
    {0x7F,0x48,0x44,0x44,0x38}, /* 'b' */
    {0x38,0x44,0x44,0x44,0x20}, /* 'c' */
    {0x38,0x44,0x44,0x48,0x7F}, /* 'd' */
    {0x38,0x54,0x54,0x54,0x18}, /* 'e' */
    {0x08,0x7E,0x09,0x01,0x02}, /* 'f' */
    {0x0C,0x52,0x52,0x52,0x3E}, /* 'g' */
    {0x7F,0x08,0x04,0x04,0x78}, /* 'h' */
    {0x00,0x44,0x7D,0x40,0x00}, /* 'i' */
    {0x20,0x40,0x44,0x3D,0x00}, /* 'j' */
    {0x7F,0x10,0x28,0x44,0x00}, /* 'k' */
    {0x00,0x41,0x7F,0x40,0x00}, /* 'l' */
    {0x7C,0x04,0x18,0x04,0x78}, /* 'm' */
    {0x7C,0x08,0x04,0x04,0x78}, /* 'n' */
    {0x38,0x44,0x44,0x44,0x38}, /* 'o' */
    {0x7C,0x14,0x14,0x14,0x08}, /* 'p' */
    {0x08,0x14,0x14,0x18,0x7C}, /* 'q' */
    {0x7C,0x08,0x04,0x04,0x08}, /* 'r' */
    {0x48,0x54,0x54,0x54,0x20}, /* 's' */
    {0x04,0x3F,0x44,0x40,0x20}, /* 't' */
    {0x3C,0x40,0x40,0x20,0x7C}, /* 'u' */
    {0x1C,0x20,0x40,0x20,0x1C}, /* 'v' */
    {0x3C,0x40,0x30,0x40,0x3C}, /* 'w' */
    {0x44,0x28,0x10,0x28,0x44}, /* 'x' */
    {0x0C,0x50,0x50,0x50,0x3C}, /* 'y' */
    {0x44,0x64,0x54,0x4C,0x44}, /* 'z' */
};

static void oled_send_cmd(uint8_t cmd)
{
    uint8_t buf[2] = {0x00, cmd};
    HAL_I2C_Master_Transmit(&hi2c1, OLED_I2C_ADDR, buf, 2, 10);
}

static void oled_init(void)
{
    HAL_Delay(100);
    const uint8_t cmds[] = {
        0xAE,             /* display off        */
        0xD5, 0x80,       /* clock divide       */
        0xA8, 0x3F,       /* multiplex 64       */
        0xD3, 0x00,       /* display offset 0   */
        0x40,             /* start line 0       */
        0x8D, 0x14,       /* charge pump on     */
        0x20, 0x00,       /* horizontal addr    */
        0xA1,             /* seg remap          */
        0xC8,             /* com scan direction */
        0xDA, 0x12,       /* com pins           */
        0x81, 0xCF,       /* contrast           */
        0xD9, 0xF1,       /* pre-charge         */
        0xDB, 0x40,       /* vcom detect        */
        0xA4,             /* all on resume      */
        0xA6,             /* normal display     */
        0xAF,             /* display on         */
    };
    for (uint32_t i = 0; i < sizeof(cmds); i++)
        oled_send_cmd(cmds[i]);
}

static void oled_clear(void)
{
    memset(oled_buf, 0, sizeof(oled_buf));
}

static void oled_draw_char(uint8_t col, uint8_t page, char c)
{
    if (c < 32 || c > 'z') c = ' ';
    const uint8_t *glyph = font5x7[c - 32];
    uint32_t idx = page * OLED_WIDTH + col;
    if (idx + 5 > sizeof(oled_buf)) return;
    for (uint8_t i = 0; i < 5; i++)
        oled_buf[idx + i] = glyph[i];
    oled_buf[idx + 5] = 0x00;   /* 1px spacing */
}

static void oled_draw_string(uint8_t col, uint8_t page, const char *str)
{
    while (*str && col < OLED_WIDTH) {
        oled_draw_char(col, page, *str++);
        col += 6;
    }
}

static void oled_flush(void)
{
    oled_send_cmd(0x21); oled_send_cmd(0); oled_send_cmd(127);  /* col 0-127  */
    oled_send_cmd(0x22); oled_send_cmd(0); oled_send_cmd(7);    /* page 0-7   */

    /* Send framebuffer in chunks of 32 bytes */
    uint8_t tx[33];
    tx[0] = 0x40;   /* data mode */
    for (uint32_t i = 0; i < sizeof(oled_buf); i += 32) {
        memcpy(&tx[1], &oled_buf[i], 32);
        HAL_I2C_Master_Transmit(&hi2c1, OLED_I2C_ADDR, tx, 33, 10);
    }
}


/* ══════════════════════════════════════════════════════════
 *  BMS — generic placeholder, swap registers once chip confirmed
 * ══════════════════════════════════════════════════════════ */
static uint8_t bms_read_soc(void)
{
    uint8_t reg = BMS_REG_SOC;
    uint8_t val = 0;
    if (HAL_I2C_Master_Transmit(&hi2c1, BMS_I2C_ADDR, &reg, 1, 10) == HAL_OK)
        HAL_I2C_Master_Receive(&hi2c1, BMS_I2C_ADDR, &val, 1, 10);
    return val;   /* raw register — scale to % once chip confirmed */
}


/* ══════════════════════════════════════════════════════════
 *  OLED DISPLAY UPDATE
 * ══════════════════════════════════════════════════════════ */
static const char *mode_names[] = {
    "Passthrough",
    "Analog ANC",
    "Digital ANC",
    "Translation",
};

static void oled_update(void)
{
    char line[22];
    uint8_t soc = bms_read_soc();

    oled_clear();
    oled_draw_string(0, 0, "-- ANURA --");
    oled_draw_string(0, 2, "Mode:");
    oled_draw_string(0, 3, mode_names[current_mode]);
    snprintf(line, sizeof(line), "Battery: %d%%", soc);
    oled_draw_string(0, 5, line);
    oled_flush();
}


/* ══════════════════════════════════════════════════════════
 *  INIT
 * ══════════════════════════════════════════════════════════ */
void anura_init(void)
{
    lms_init(&lms_left);
    lms_init(&lms_right);

    /* Start in passthrough, digital path */
    current_mode = MODE_PASSTHROUGH;
    set_ad_ctrl(1);

    /* OLED */
    oled_init();
    oled_update();

    /* ADC DMA — 4 channels, circular, timer-triggered */
    HAL_ADC_Start_DMA(&hadc1, (uint32_t *)adc_buf, ADC_BUF_LEN);

    /* DAC DMA — dual channel */
    HAL_DAC_Start_DMA(&hdac, DAC_CHANNEL_1,
                      (uint32_t *)dac_buf,
                      ADC_BUF_FRAMES, DAC_ALIGN_12B_R);
    HAL_DAC_Start_DMA(&hdac, DAC_CHANNEL_2,
                      (uint32_t *)&dac_buf[0].right,
                      ADC_BUF_FRAMES, DAC_ALIGN_12B_R);

    /* Sample rate timer */
    HAL_TIM_Base_Start(&htim2);

    /* Button debounce timer */
    HAL_TIM_Base_Start_IT(&htim4);
}


/* ══════════════════════════════════════════════════════════
 *  MAIN LOOP — call anura_init() then anura_run() from main()
 * ══════════════════════════════════════════════════════════ */
void anura_run(void)
{
    uint32_t last_display_tick = 0;

    while (1) {
        /* Check button — switches mode if debounced press detected */
        AnuraMode prev = current_mode;
        button_check();

        /* Refresh OLED every 500ms or on mode change */
        uint32_t now = HAL_GetTick();
        if (current_mode != prev || (now - last_display_tick) >= 500) {
            oled_update();
            last_display_tick = now;
        }

        /* Audio processing happens entirely in DMA callbacks —
         * nothing audio-related needed here in the main loop. */
    }
}


/* ══════════════════════════════════════════════════════════
 *  CubeMX CONFIGURATION CHECKLIST
 * ──────────────────────────────────────────────────────────
 *
 *  ADC1  Scan mode, 4 channels, right-align, 12-bit
 *    Rank 1  IN2  (PA2)  84 cycles  ← left outer MEMS mic
 *    Rank 2  IN3  (PA3)  84 cycles  ← right outer MEMS mic
 *    Rank 3  IN6  (PA6)  84 cycles  ← left audio in
 *    Rank 4  IN7  (PA7)  84 cycles  ← right audio in
 *    External trigger: TIM2 TRGO, rising edge
 *    DMA: DMA2 Stream0 Ch0, circular, HalfWord→HalfWord
 *    Enable DMA half-transfer + transfer-complete interrupts
 *
 *  DAC
 *    Ch1 (PA4): trigger TIM2 TRGO, DMA1 Stream5 Ch7, output buffer ON
 *    Ch2 (PA5): trigger TIM2 TRGO, DMA1 Stream6 Ch7, output buffer ON
 *
 *  TIM2  (sample rate)
 *    Internal clock, prescaler 0
 *    ARR = 1749  → 84MHz / 1750 = 48kHz
 *    TRGO: Update event
 *
 *  TIM3  (PWM mono mic out)
 *    CH3 on PB0, PWM mode 1
 *    Prescaler 0, ARR = 4095
 *    CCR3 set dynamically in firmware
 *
 *  TIM4  (button debounce)
 *    Internal clock, prescaler 83, ARR = 999
 *    → 84MHz / 84 / 1000 = 1kHz = 1ms tick
 *    Enable update interrupt in NVIC
 *
 *  I2C1
 *    PB6 SCL, PB7 SDA
 *    Fast mode 400kHz
 *
 *  GPIO
 *    PA8: GPIO_Input, Pull-Down  ← mode button
 *    PB4: GPIO_Output, Push-Pull, no pull, init LOW
 *
 *  NVIC priorities
 *    DMA2_Stream0: 0 (highest — audio ISR)
 *    TIM4:         1 (button debounce)
 *    I2C1:         2
 * ══════════════════════════════════════════════════════════ */
